config:
  target: "http://localhost:3000"
  phases:
    - duration: 30
      arrivalRate: 300    
scenarios:
  - flow:
      - loop:
          - get:
              url: "/shoe/{{ $loopElement }}"
        over: 
          - 1
          - 2
          - 3
          - 99
          - 67
          - 54
          - 101
